### ISSUE TITLE
Example workflow

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/fedora-action#1]
```yaml
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say moo
        uses: gbraad-actions/fedora-action@main
        with:
          dnf-packages: cowsay
          run: |
            cowsay Moo
```
```
 _______
<  Moo  >
 -------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
